Rename tag for better consistency.

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,299 +1,222 @@
-#!/bin/sh
-#
-# Copyright by The HDF Group.
-# Copyright by the Board of Trustees of the University of Illinois.
-# All rights reserved.
-#
-# This file is part of HDF5.  The full HDF5 copyright notice, including
-# terms governing use, modification, and redistribution, is contained in
-# the files COPYING and Copyright.html.  COPYING can be found at the root
-# of the source code distribution tree; Copyright.html can be found at the
-# root level of an installed copy of the electronic HDF5 document set and
-# is linked from the top-level documents page.  It can also be found at
-# http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
-# access to either file, you may request a copy from help@hdfgroup.org.
-#
+#! /usr/local/bin/perl -w
+require 5.003;
+use Cwd;
 
-# Make a release of hdf5.  The command-line switches are:
+# Builds a release.  Arguments are zero or more of the words.
 #
-#  -d DIR	The name of the directory where the releas(es) should be
-#               placed.  By default, the directory is ./releases
+#	tar		-- build a tar file			*.tar
+#	compress	-- build a compressed tar file		*.tar.Z
+#	gzip		-- build a compressed tar file		*.tar.gz
+#	bzip2		-- build a compressed tar file		*.tar.bz2
 #
-#  --nocheck	Ignore errors in MANIFEST file.
-#          
-#  --private	Make a private release with today's date in version information.
-#          
-# The other command-line options are the names of the programs to use
-# for compressing the resulting tar archive (if none are given then
-# `tar md5' is assumed):
-#
-#   tar		-- use tar and don't do any compressing.
-#   compress	-- use compress and append `.Z' to the output name.
-#   gzip	-- use gzip with `-9' and append `.gz' to the output name.
-#   bzip2       -- use bzip2 with `-9' and append `.bz2' to the output name.
-#   md5         -- produce a md5 checksum in addition to the archive.
-#   doc         -- produce the latest doc tree in addition to the archive.
-#
-# Examples:
-#
-#   $ release
-#   releases/hdf5-1.0.38.tar
-#   releases/hdf5-1.0.38.tar.md5
-#
-#   $ release gzip
-#   releases/hdf5-1.0.38.tar.gz
-#
-#   $ release -d /tmp tar compress gzip bzip2 md5 doc
-#   /tmp/hdf5-1.0.38.tar
-#   /tmp/hdf5-1.0.38.tar.Z
-#   /tmp/hdf5-1.0.38.tar.gz
-#   /tmp/hdf5-1.0.38.tar.bz2
-#   /tmp/hdf5-1.0.38.tar.md5
-#   /tmp/hdf5-1.0.38_doc.tar
-#
-# Modifications
-#   Robb Matzke, 1999-07-16
-#   The SunOS 5.6 sed *must* have slashes as delimiters. I changed things like
-#   `sed s+/CVS++' to `sed 's/\/CVS//'
-#
-#   Albert Cheng, 1999-10-26
-#   Moved the MANIFEST checking to a separate command file so that
-#   it can be invoked individually.
+# If no arguments are given then `gzip' is assumed.  If the only argument
+# is the word `all' then all forms are used.
 
-# Function definitions
+$releases = "./releases";	# Directory for release tarballs
+
+##############################################################################
+# Read version info, return an array (MAJOR,MINOR,RELEASE,PATCHLEVEL) or
+# a string "MAJOR.MINOR.RELEASE PATCHLEVEL"
 #
-# Print Usage page
-USAGE()
-{
-cat << EOF
-Usage: $0 [--nocheck] [-d <dir>] [-h] <methods> ...
-   -d DIR	The name of the directory where the releas(es) should be
-                placed.  By default, the directory is ./releases
+sub getver () {
+   my @ver;
 
-   --nocheck	Ignore errors in MANIFEST file.
-         
-   --private	Make a private release with today's date in version information.
-         
-The other command-line options are the names of the programs to use
-for compressing the resulting tar archive (if none are given then
-"tar md5" is assumed):
+   open SRC, "./src/H5private.h" or die "cannot read HDF5 version";
+   while (<SRC>) {
+      $ver[0] = $1 if /define\s+HDF5_MAJOR_VERSION\s+(\d+)/;
+      $ver[1] = $1 if /define\s+HDF5_MINOR_VERSION\s+(\d+)/;
+      $ver[2] = $1 if /define\s+HDF5_RELEASE_VERSION\s+(\d+)/;
+      $ver[3] = $1 if /define\s+HDF5_PATCH_VERSION\s+(\d+)/;
+   }
+   close SRC;
+   wantarray ? @ver : "$ver[0].$ver[1].$ver[2]".chr(ord('a')+$ver[3]);
+}
 
-    tar		-- use tar and don't do any compressing.
-    compress	-- use compress and append ".Z" to the output name.
-    gzip	-- use gzip with "-9" and append ".gz" to the output name.
-    bzip2       -- use bzip2 with "-9" and append ".bz2" to the output name.
-    md5         -- produce a md5 checksum in addition to the archive.
-    doc         -- produce the latest doc tree in addition to the archive.
+##############################################################################
+# Set version information.  Input is a string or an array.
+#
+sub setver ($;$$$) {
+   my @ver = @_;
+   local $_;
 
-Examples:
+   if ($ver[0]=~/\D/) {
+      @ver = $ver[0] =~ /^(\d+)\.(\d+)\.(\d+)([a-z])$/ or return "";
+      $ver[3] = ord($ver[3])-ord('a');
+   }
 
-    $ release
-    releases/hdf5-1.0.38.tar
-    releases/hdf5-1.0.38.tar.md5
+   $_ = `cat ./src/H5private.h`;
+   s/(define\s+HDF5_MAJOR_VERSION\s+)(\d+)/$1$ver[0]/;
+   s/(define\s+HDF5_MINOR_VERSION\s+)(\d+)/$1$ver[1]/;
+   s/(define\s+HDF5_RELEASE_VERSION\s+)(\d+)/$1$ver[2]/;
+   s/(define\s+HDF5_PATCH_VERSION\s+)(\d+)/$1$ver[3]/;
+   open SRC, "> ./src/H5private.h" or return "";
+   print SRC $_;
+   close SRC;
 
-    $ release gzip
-    releases/hdf5-1.0.38.tar.gz
+   return 1;
+}
 
-    $ release -d /tmp tar compress gzip bzip2 md5
-    /tmp/hdf5-1.0.38.tar
-    /tmp/hdf5-1.0.38.tar.Z
-    /tmp/hdf5-1.0.38.tar.gz
-    /tmp/hdf5-1.0.38.tar.bz2
-    /tmp/hdf5-1.0.38.tar.md5
+##############################################################################
+# Make sure MANIFEST contains all the necessary files.  If we are running
+# under CVS then look at the CVS/Entries files to get the names that should
+# be in the manifest.  Otherwise we really can't do anything.
+#
+sub manifest () {
+    my ($fname, %manifest);
+    my $nprobs=0;
+
+    # We can't do anything if we're not running under cvs.
+    return "" unless -d "CVS";
+
+    # Read the files from the manifest.
+    open MANIFEST, "MANIFEST" or die "unable to read manifest";
+    while (<MANIFEST>) {
+	chomp;
+	$manifest{$_} = 1;
+    }
+    close MANIFEST;
+
+    # Read files from CVS/Entries
+    open FIND, "find . -name Entries -print | sort |" or
+	die "unable to find CVS entries";
+    while ($fname=<FIND>) {
+	chomp $fname;
+	my ($dir) = $fname =~ m%(.*)/CVS/Entries%;
+	open ENTRIES, $fname or die "unable to open $fname";
+	while (<ENTRIES>) {
+	    my ($ename) = m%^/(.*?)/%;
+	    $ename = "$dir/" . $ename;
+	    if (exists $manifest{$ename}) {
+		delete $manifest{$ename};
+	    } else {
+		print "NEW: $ename\n";
+		$nprobs++;
+	    }
+	}
+	close ENTRIES;
+    }
+    close FIND;
+
+    for (sort keys %manifest) {
+	print "OLD: $_\n";
+	$nprobs++;
+    }
+
+    if ($nprobs) {
+	print "Please add the new files to MANIFEST and remove the old\n";
+	print "files and try again.  The MANIFEST should contain all files\n";
+	print "that are to be distributed for a release.\n";
+	exit 1;
+    }
+}
+
+
+##############################################################################
+# Build a release
+#
+sub release (@) {
+   my @types = @_;
+   my ($ver, $status, $created_symlink);
+   local $_;
+
+   # Make sure no one forgot to update MANIFEST
+   manifest;
+
+   # Make sure the version number is correct.
+   print "Building an HDF release...\n";
+   print "HDF version to release [", ($ver=getver), "] ";
+   return "" unless defined ($_=<STDIN>);
+   chomp;
+   (setver ($ver=$_) or die "cannot set version") if /\S/;
+
+   # Clean the source tree, showing only errors.
+   print "Cleaning source tree...\n";
+   $status = system "make distclean >/dev/null";
+   die "cannot make distclean" if $status >> 8;
+
+   # Move default top-level makefile into place.
+   $status = system "cp Makefile.dist Makefile";
+   die "cannot install default Makefile" if $status >> 8;
+
+   # Make sure release directory exists
+   (mkdir $releases, 0777 or die "cannot create $releases")
+       unless -d $releases;
+   die "no manifest" unless -r "MANIFEST";
+
+   # We build the release from above the root of the source tree so the
+   # hdf5 directory appears as part of the name in the tar file. We create
+   # a temporary symlink called something like `hdf5-1.0.0a' that points to
+   # our current working directory.
+   $_ = cwd;
+   my ($parent,$root) = m%(.*)/(.*)$% or die "cannot split directory";
+   if ($root ne "hdf5-$ver" && ! -e "../hdf5-$ver") {
+      symlink $root, "../hdf5-$ver" or die "cannot create link";
+      $created_symlink = 1;
+   }
+   my $name = "$root/$releases/hdf5-$ver";
+
+   # Build the releases.
+   @types = ("gzip") unless @types;
+   @types = qw/tar gzip compress bzip2/ if 1==@types && "all" eq $types[0];
+   $_ = `cat MANIFEST`;
+   s/^\.\///mg;
+   @filelist = ("Makefile", split /\s*\n/, $_);
+   $filelist = join " ", map {"hdf5-$ver/$_"} @filelist;
+
+   chdir ".." or die;
+   for (@types) {
+      print "Compressing with $_...\n";
+
+      /^tar$/ && do {
+	 $status = system "tar cf $name.tar $filelist";
+	 next;
+      };
+
+      /^gzip$/ && do {
+	 $status = system "tar cf - $filelist |gzip -9 >$name.tar.gz";
+	 next;
+      };
+
+      /^compress$/ && do {
+	 $status = system "tar cf - $filelist |compress -c >$name.tar.Z";
+	 next;
+      };
+
+      /^bzip2$/ && do {
+	 $status = system "tar cf - $filelist |bzip2 -9 >$name.tar.bz2";
+	 next;
+      };
+   } continue {
+      print STDERR "$_ failed\n" if $status >> 8;
+   }
+   chdir $root or die;
+
+   # Remove the temporary symlink we created above.
+   unlink "../hdf5-$ver" if $created_symlink;
+   
+
+   # Update version info
+   print <<EOF;
+
+If this is a real release then the version number for continued development
+should be incremented.  Otherwise just press return.
 
 EOF
+   print "Set development version to [", ($ver=getver), "] ";
+   return "" unless defined ($_ = <STDIN>);
+   chomp;
+   (setver ($ver=$_) or die "cannot set version") if /\S/;
 
+   if (-d "CVS") {
+      print <<EOF;
+      # If we're running under CVS then check in changes and tag all files
+      # with the release number.  Quincey, do you want to add this to the
+      # bottom of the perl script?  Otherwise just give me the commands
+      # and I'll add them.
+EOF
+   }
+
+   return 1;
 }
 
-# This command must be run at the top level of the hdf5 source directory.
-# Verify this requirement.
-if [ ! \( -f configure -a -f bin/release \) ]; then
-    echo "$0 must be run at the top level of the hdf5 source directory"
-    exit 1
-fi
-
-# Defaults
-DEST=releases
-VERS=`perl bin/h5vers`
-VERS_OLD=
-test "$VERS" || exit 1
-verbose=yes
-check=yes
-today=`date +%Y%m%d`
-pmode='no'
-tmpdir="../#release_tmp.$$"	# tmp work directory
-DOC_URL=http://svn.hdfgroup.uiuc.edu/hdf5doc/trunk
-CPPLUS_RM_NAME=cpplus_RM
-
-# Restore previous Version information
-RESTORE_VERSION()
-{
-    if [ X-${VERS_OLD} != X- ]; then
-	echo restoring version information back to $VERS_OLD
-	rm -f config/lt_vers.am
-	cp $tmpdir/lt_vers.am config/lt_vers.am
-	bin/h5vers -s $VERS_OLD
-	VERS_OLD=
-    fi
-}
-
-
-# Command-line arguments
-while [ -n "$1" ]; do
-    arg=$1
-    shift
-    case "$arg" in
-	-d)
-	    DEST=$1
-	    shift
-	    ;;
-	--nocheck)
-	    check=no
-	    ;;
-	-h)
-	    USAGE
-	    exit 0
-	    ;;
-	--private)
-	    pmode=yes
-	    ;;
-	-*)
-	    echo "Unknown switch: $arg" 1>&2
-	    USAGE
-	    exit 1
-	    ;;
-	*)
-	    methods="$methods $arg"
-	    ;;
-    esac
-done
-
-# Default methods are tar and md5
-if [ "X$methods" = "X" ]; then
-    methods="tar md5"
-fi
-
-# Create the temporay work directory.
-if mkdir $tmpdir; then
-    echo "temporary work directory for release.  "\
-         "Can be deleted after release completes." > $tmpdir/README
-else
-    echo "Failed to mkdir tmpdir($tmpdir)"
-    exit 1
-fi
-
-# setup restoration in case of abort.
-trap RESTORE_VERSION 0
-
-if [ X$pmode = Xyes ]; then
-    VERS_OLD=$VERS
-    # Copy old version of config/lt_vers.am, since it's hard to
-    # "undo" changes to it.
-    cp config/lt_vers.am $tmpdir
-    # Set version information to m.n.r-of$today.
-    # (h5vers does not correctly handle just m.n.r-$today.)
-    VERS=`echo $VERS | sed -e s/-.*//`-of$today
-    echo Private release of $VERS
-    bin/h5vers -s $VERS
-fi
-
-# Store hdf5-$VERS ("hdf5-1.7.51", e.g.) to a variable to avoid typos
-HDF5_VERS=hdf5-$VERS
-
-test "$verbose" && echo "Releasing $HDF5_VERS to $DEST" 1>&2
-if [ ! -d $DEST ]; then
-    echo "   Destination directory $DEST does not exist" 1>&2
-    exit 1
-fi
-
-# Check the validity of the MANIFEST file.
-bin/chkmanifest || fail=yes
-if [ "X$fail" = "Xyes" ]; then
-    if [ $check = yes ]; then
-        exit 1
-    else
-	echo "Continuing anyway..."
-    fi
-fi
-
-# Create a manifest that contains only files for distribution.
-MANIFEST=$tmpdir/H5_MANIFEST
-grep '^\.' MANIFEST | grep -v _DO_NOT_DISTRIBUTE_ >$MANIFEST
-
-# Prepare the source tree for a release.
-ln -s `pwd` $tmpdir/$HDF5_VERS || exit 1
-mv Makefile $tmpdir/Makefile.x 2>/dev/null #might fail
-cp -p Makefile.dist Makefile
-
-# Update README.txt and release_docs/RELEASE.txt with release information.
-for f in README.txt release_docs/RELEASE.txt; do
-    echo "HDF5 version $VERS released on `date`" >$f.x
-    tail +2l $f >>$f.x
-    mv $f.x $f
-    # Make sure new files are of the right access mode
-    chmod 644 $f
-done
-
-# Create the tar file
-test "$verbose" && echo "   Running tar..." 1>&2
-( \
-    cd $tmpdir; \
-    tar cf $HDF5_VERS.tar $HDF5_VERS/Makefile \
-	`sed 's/^\.\//hdf5-'$VERS'\//' $MANIFEST` || exit 1 \
-)
-
-# Compress
-for comp in $methods; do
-    case $comp in
-	tar)
-	    cp -p $tmpdir/$HDF5_VERS.tar $DEST/$HDF5_VERS.tar
-	    ;;
-	compress)
-	    test "$verbose" && echo "   Running compress..." 1>&2
-	    compress -c <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.Z
-	    ;;
-	gzip)
-	    test "$verbose" && echo "   Running gzip..." 1>&2
-	    gzip -9 <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.gz
-	    ;;
-	bzip2)
-	    test "$verbose" && echo "   Running bzip2..." 1>&2
-	    bzip2 -9 <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.bz2
-	    ;;
-	md5)
-	    test "$verbose" && echo "   Creating checksum..." 1>&2
-	    (cd $tmpdir; md5sum $HDF5_VERS.tar ) > $DEST/$HDF5_VERS.tar.md5
-	    ;;
-	doc)
-	    test "$verbose" && echo "   Creating docs..." 1>&2
-	    # Check out docs from svn repo
-	    (cd $tmpdir; svn co $DOC_URL > /dev/null) || exit 1
-	    # Create doxygen C++ RM
-	    (cd c++/src && doxygen cpp_doc_config > /dev/null ) || exit 1
-	    # Replace version of C++ RM with just-created version
-	    rm -rf $tmpdir/trunk/html/$CPPLUS_RM_NAME
-	    mv c++/src/$CPPLUS_RM_NAME $tmpdir/trunk/html/$CPPLUS_RM_NAME
-	    # Compress the docs and move them to the release area
-	    mv $tmpdir/trunk $tmpdir/${HDF5_VERS}_docs
-	    (cd $tmpdir && tar cf ${HDF5_VERS}_docs.tar ${HDF5_VERS}_docs)
-	    mv $tmpdir/${HDF5_VERS}_docs.tar $DEST
-	    ;;
-    esac
-done
-
-# Copy the RELEASE.txt to the release area.
-cp release_docs/RELEASE.txt $DEST/$HDF5_VERS-RELEASE.txt
-
-# Restore previous Makefile if existed.
-test -f $tmpdir/Makefile.x && mv $tmpdir/Makefile.x Makefile
-
-# Restore OLD version information, then no need for trap.
-if [ X$pmode = Xyes ]; then
-    RESTORE_VERSION
-    trap 0
-fi
-
-# Remove temporary things
-rm -rf $tmpdir
-
-exit 0
+release @ARGV;
