Fix typo in last tag rename.

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,6 +1,5 @@
 #!/bin/sh
 #
-# Copyright by The HDF Group.
 # Copyright by the Board of Trustees of the University of Illinois.
 # All rights reserved.
 #
@@ -10,8 +9,8 @@
 # of the source code distribution tree; Copyright.html can be found at the
 # root level of an installed copy of the electronic HDF5 document set and
 # is linked from the top-level documents page.  It can also be found at
-# http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
-# access to either file, you may request a copy from help@hdfgroup.org.
+# http://hdf.ncsa.uiuc.edu/HDF5/doc/Copyright.html.  If you do not have
+# access to either file, you may request a copy from hdfhelp@ncsa.uiuc.edu.
 #
 
 # Make a release of hdf5.  The command-line switches are:
@@ -21,35 +20,28 @@
 #
 #  --nocheck	Ignore errors in MANIFEST file.
 #          
-#  --private	Make a private release with today's date in version information.
-#          
 # The other command-line options are the names of the programs to use
 # for compressing the resulting tar archive (if none are given then
-# `tar md5' is assumed):
+# `tar' is assumed):
 #
 #   tar		-- use tar and don't do any compressing.
 #   compress	-- use compress and append `.Z' to the output name.
 #   gzip	-- use gzip with `-9' and append `.gz' to the output name.
 #   bzip2       -- use bzip2 with `-9' and append `.bz2' to the output name.
-#   md5         -- produce a md5 checksum in addition to the archive.
-#   doc         -- produce the latest doc tree in addition to the archive.
 #
 # Examples:
 #
 #   $ release
 #   releases/hdf5-1.0.38.tar
-#   releases/hdf5-1.0.38.tar.md5
 #
 #   $ release gzip
 #   releases/hdf5-1.0.38.tar.gz
 #
-#   $ release -d /tmp tar compress gzip bzip2 md5 doc
+#   $ release -d /tmp tar compress gzip bzip2
 #   /tmp/hdf5-1.0.38.tar
 #   /tmp/hdf5-1.0.38.tar.Z
 #   /tmp/hdf5-1.0.38.tar.gz
 #   /tmp/hdf5-1.0.38.tar.bz2
-#   /tmp/hdf5-1.0.38.tar.md5
-#   /tmp/hdf5-1.0.38_doc.tar
 #
 # Modifications
 #   Robb Matzke, 1999-07-16
@@ -60,83 +52,12 @@
 #   Moved the MANIFEST checking to a separate command file so that
 #   it can be invoked individually.
 
-# Function definitions
-#
-# Print Usage page
-USAGE()
-{
-cat << EOF
-Usage: $0 [--nocheck] [-d <dir>] [-h] <methods> ...
-   -d DIR	The name of the directory where the releas(es) should be
-                placed.  By default, the directory is ./releases
-
-   --nocheck	Ignore errors in MANIFEST file.
-         
-   --private	Make a private release with today's date in version information.
-         
-The other command-line options are the names of the programs to use
-for compressing the resulting tar archive (if none are given then
-"tar md5" is assumed):
-
-    tar		-- use tar and don't do any compressing.
-    compress	-- use compress and append ".Z" to the output name.
-    gzip	-- use gzip with "-9" and append ".gz" to the output name.
-    bzip2       -- use bzip2 with "-9" and append ".bz2" to the output name.
-    md5         -- produce a md5 checksum in addition to the archive.
-    doc         -- produce the latest doc tree in addition to the archive.
-
-Examples:
-
-    $ release
-    releases/hdf5-1.0.38.tar
-    releases/hdf5-1.0.38.tar.md5
-
-    $ release gzip
-    releases/hdf5-1.0.38.tar.gz
-
-    $ release -d /tmp tar compress gzip bzip2 md5
-    /tmp/hdf5-1.0.38.tar
-    /tmp/hdf5-1.0.38.tar.Z
-    /tmp/hdf5-1.0.38.tar.gz
-    /tmp/hdf5-1.0.38.tar.bz2
-    /tmp/hdf5-1.0.38.tar.md5
-
-EOF
-
-}
-
-# This command must be run at the top level of the hdf5 source directory.
-# Verify this requirement.
-if [ ! \( -f configure -a -f bin/release \) ]; then
-    echo "$0 must be run at the top level of the hdf5 source directory"
-    exit 1
-fi
-
 # Defaults
 DEST=releases
 VERS=`perl bin/h5vers`
-VERS_OLD=
 test "$VERS" || exit 1
 verbose=yes
 check=yes
-today=`date +%Y%m%d`
-pmode='no'
-tmpdir="../#release_tmp.$$"	# tmp work directory
-DOC_URL=http://svn.hdfgroup.uiuc.edu/hdf5doc/trunk
-CPPLUS_RM_NAME=cpplus_RM
-
-# Restore previous Version information
-RESTORE_VERSION()
-{
-    if [ X-${VERS_OLD} != X- ]; then
-	echo restoring version information back to $VERS_OLD
-	rm -f config/lt_vers.am
-	cp $tmpdir/lt_vers.am config/lt_vers.am
-	bin/h5vers -s $VERS_OLD
-	VERS_OLD=
-    fi
-}
-
 
 # Command-line arguments
 while [ -n "$1" ]; do
@@ -150,16 +71,8 @@ while [ -n "$1" ]; do
 	--nocheck)
 	    check=no
 	    ;;
-	-h)
-	    USAGE
-	    exit 0
-	    ;;
-	--private)
-	    pmode=yes
-	    ;;
 	-*)
 	    echo "Unknown switch: $arg" 1>&2
-	    USAGE
 	    exit 1
 	    ;;
 	*)
@@ -168,39 +81,13 @@ while [ -n "$1" ]; do
     esac
 done
 
-# Default methods are tar and md5
+# Default method is tar
 if [ "X$methods" = "X" ]; then
-    methods="tar md5"
+    methods=tar
 fi
 
-# Create the temporay work directory.
-if mkdir $tmpdir; then
-    echo "temporary work directory for release.  "\
-         "Can be deleted after release completes." > $tmpdir/README
-else
-    echo "Failed to mkdir tmpdir($tmpdir)"
-    exit 1
-fi
 
-# setup restoration in case of abort.
-trap RESTORE_VERSION 0
-
-if [ X$pmode = Xyes ]; then
-    VERS_OLD=$VERS
-    # Copy old version of config/lt_vers.am, since it's hard to
-    # "undo" changes to it.
-    cp config/lt_vers.am $tmpdir
-    # Set version information to m.n.r-of$today.
-    # (h5vers does not correctly handle just m.n.r-$today.)
-    VERS=`echo $VERS | sed -e s/-.*//`-of$today
-    echo Private release of $VERS
-    bin/h5vers -s $VERS
-fi
-
-# Store hdf5-$VERS ("hdf5-1.7.51", e.g.) to a variable to avoid typos
-HDF5_VERS=hdf5-$VERS
-
-test "$verbose" && echo "Releasing $HDF5_VERS to $DEST" 1>&2
+test "$verbose" && echo "Releasing hdf5-$VERS to $DEST" 1>&2
 if [ ! -d $DEST ]; then
     echo "   Destination directory $DEST does not exist" 1>&2
     exit 1
@@ -217,12 +104,13 @@ if [ "X$fail" = "Xyes" ]; then
 fi
 
 # Create a manifest that contains only files for distribution.
-MANIFEST=$tmpdir/H5_MANIFEST
+MANIFEST=/tmp/H5_MANIFEST.$$
 grep '^\.' MANIFEST | grep -v _DO_NOT_DISTRIBUTE_ >$MANIFEST
 
 # Prepare the source tree for a release.
-ln -s `pwd` $tmpdir/$HDF5_VERS || exit 1
-mv Makefile $tmpdir/Makefile.x 2>/dev/null #might fail
+test -h ../hdf5-$VERS && rm ../hdf5-$VERS
+ln -s `pwd` ../hdf5-$VERS || exit 1
+mv Makefile ../Makefile.x 2>/dev/null #might fail
 cp -p Makefile.dist Makefile
 
 # Update README.txt and release_docs/RELEASE.txt with release information.
@@ -234,11 +122,14 @@ for f in README.txt release_docs/RELEASE.txt; do
     chmod 644 $f
 done
 
+# synchronize the HISTORY.tx and RELEASE.tx files in the doc area
+cp release_docs/HISTORY.txt release_docs/RELEASE.txt doc/html/ADGuide/.
+
 # Create the tar file
 test "$verbose" && echo "   Running tar..." 1>&2
 ( \
-    cd $tmpdir; \
-    tar cf $HDF5_VERS.tar $HDF5_VERS/Makefile \
+    cd ..; \
+    tar cf x.tar hdf5-$VERS/Makefile \
 	`sed 's/^\.\//hdf5-'$VERS'\//' $MANIFEST` || exit 1 \
 )
 
@@ -246,54 +137,25 @@ test "$verbose" && echo "   Running tar..." 1>&2
 for comp in $methods; do
     case $comp in
 	tar)
-	    cp -p $tmpdir/$HDF5_VERS.tar $DEST/$HDF5_VERS.tar
-	    ;;
+	    cp -p ../x.tar $DEST/hdf5-$VERS.tar;;
 	compress)
 	    test "$verbose" && echo "   Running compress..." 1>&2
-	    compress -c <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.Z
-	    ;;
+	    compress -c <../x.tar >$DEST/hdf5-$VERS.tar.Z;;
 	gzip)
 	    test "$verbose" && echo "   Running gzip..." 1>&2
-	    gzip -9 <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.gz
-	    ;;
+	    gzip -9 <../x.tar >$DEST/hdf5-$VERS.tar.gz;;
 	bzip2)
 	    test "$verbose" && echo "   Running bzip2..." 1>&2
-	    bzip2 -9 <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.bz2
-	    ;;
-	md5)
-	    test "$verbose" && echo "   Creating checksum..." 1>&2
-	    (cd $tmpdir; md5sum $HDF5_VERS.tar ) > $DEST/$HDF5_VERS.tar.md5
-	    ;;
-	doc)
-	    test "$verbose" && echo "   Creating docs..." 1>&2
-	    # Check out docs from svn repo
-	    (cd $tmpdir; svn co $DOC_URL > /dev/null) || exit 1
-	    # Create doxygen C++ RM
-	    (cd c++/src && doxygen cpp_doc_config > /dev/null ) || exit 1
-	    # Replace version of C++ RM with just-created version
-	    rm -rf $tmpdir/trunk/html/$CPPLUS_RM_NAME
-	    mv c++/src/$CPPLUS_RM_NAME $tmpdir/trunk/html/$CPPLUS_RM_NAME
-	    # Compress the docs and move them to the release area
-	    mv $tmpdir/trunk $tmpdir/${HDF5_VERS}_docs
-	    (cd $tmpdir && tar cf ${HDF5_VERS}_docs.tar ${HDF5_VERS}_docs)
-	    mv $tmpdir/${HDF5_VERS}_docs.tar $DEST
-	    ;;
+	    bzip2 -9 <../x.tar >$DEST/hdf5-$VERS.tar.bz2;;
     esac
 done
 
 # Copy the RELEASE.txt to the release area.
-cp release_docs/RELEASE.txt $DEST/$HDF5_VERS-RELEASE.txt
-
-# Restore previous Makefile if existed.
-test -f $tmpdir/Makefile.x && mv $tmpdir/Makefile.x Makefile
-
-# Restore OLD version information, then no need for trap.
-if [ X$pmode = Xyes ]; then
-    RESTORE_VERSION
-    trap 0
-fi
+cp release_docs/RELEASE.txt $DEST/hdf5-$VERS-RELEASE.txt
 
 # Remove temporary things
-rm -rf $tmpdir
-
+test -f ../Makefile.x && mv ../Makefile.x Makefile
+rm -f $MANIFEST
+rm -f ../hdf5-$VERS
+rm -f ../x.tar
 exit 0
diff --git a/bin/snapshot b/bin/snapshot
--- a/bin/snapshot
+++ b/bin/snapshot
@@ -1,6 +1,5 @@
 #!/bin/sh
 #
-# Copyright by The HDF Group.
 # Copyright by the Board of Trustees of the University of Illinois.
 # All rights reserved.
 #
@@ -10,56 +9,30 @@
 # of the source code distribution tree; Copyright.html can be found at the
 # root level of an installed copy of the electronic HDF5 document set and
 # is linked from the top-level documents page.  It can also be found at
-# http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
-# access to either file, you may request a copy from help@hdfgroup.org.
-
+# http://hdf.ncsa.uiuc.edu/HDF5/doc/Copyright.html.  If you do not have
+# access to either file, you may request a copy from hdfhelp@ncsa.uiuc.edu.
+#
+echo "====================================="
+echo "$0 $*"
+echo "====================================="
+set -x
+date
+uname -a
+#
 # This script should be run nightly from cron.  It checks out hdf5
-# from the source repository and compares it against the previous
+# from the CVS source tree and compares it against the previous
 # snapshot.  If anything significant changed then a new snapshot is
 # created, the minor version number is incremented, and the change is
-# checked back into the source repository.
+# checked back into the CVS repository.
 #
 
-# function definitions
-TIMESTAMP()
-{
-    echo "=====" "$1": "`date`" "====="
-}
+# The path isn't properly initialized on hawkwind -- /usr/local/bin is
+# either missing or is after /usr/bin when it should be before.
+PATH="/usr/local/bin:$PATH"
 
-EXIT_BANNER()
-{
-TIMESTAMP "Exit $PROGNAME with status=$?"
-}
-
-# Show current total disk usage.
-DISKUSAGE()
-{
-    du -ks | \
-    ( read x y; echo "Disk Usage=$x KB" )
-}
-
-
-# MAIN
-# SGI /bin/sh replaces $0 as function name if used in a function.
-# Set the name here to avoid that ambiguity and better style too.
-PROGNAME=$0
-
-echo "====================================="
-echo "$PROGNAME $*"
-echo "====================================="
-TIMESTAMP MAIN
-uname -a
-
-# setup exit banner message
-trap EXIT_BANNER 0
-
-# Dump environment variables before option parsing
-echo ===Dumping environment variables before option parsing ===
-printenv | sort
-echo ===Done Dumping environment variables before option parsing ===
-
-# snapshots release directory.  Default relative to $BASEDIR.
-ReleaseDir_default=release_dir
+# Where are the snapshots stored?
+ARCHIVES_default=/afs/ncsa/ftp/HDF/pub/outgoing/hdf5/snapshots
+ARCHIVES=$ARCHIVES_default
 
 # Where is the zlib library?
 # At NCSA, half of the machines have it in /usr/lib, the other half at
@@ -67,14 +40,17 @@ ReleaseDir_default=release_dir
 ZLIB_default=
 ZLIB=$ZLIB_default
 
-# What compression methods to use? (md5 does checksum).
-METHODS="gzip bzip2 md5 doc"
+# What compression methods to use?
+METHODS="gzip bzip2"
 
 # Use User's MAKE if set.  Else use generic make.
 MAKE=${MAKE:-make}
 
-# Default check action.
-CHECKVAL=check
+# Make sure cvs would work
+if [ -z "$CVSROOT" ]; then
+    echo "Where is the CVS repository?" 1>&2
+    exit 1
+fi
 
 #
 # Command options
@@ -94,57 +70,9 @@ while [ $# -gt 0 ] ; do
 	    cmddiff="diff"
 	    cmd=""
 	    ;;
-	deploy)
-	    # deploy the built binary.
-	    shift
-	    if [ $# -lt 1 ]; then
-		echo "deploy <dir> missing"
-		errcode=1
-		cmd="help"
-		break
-	    fi
-	    cmddeploy="deploy"
-	    DEPLOYDIRNAME="$1"
-	    ;;
-	deploydir)
-	    # default directory for deployment.
-	    shift
-	    if [ $# -lt 1 ]; then
-		echo "deploydir <dir> missing"
-		errcode=1
-		cmd="help"
-		break
-	    fi
-	    deploydir="$1"
-	    ;;
 	test)
 	    cmdtest="test"
 	    cmd=""
-	    ;;
-	setenv)
-	    # set environment variable
-	    shift
-	    eval $1="$2"
-	    export $1
-	    shift
-	    ;;
-	setenvN)
-	    # set environment variable with $1 values
-	    # e.g., setenvN 3 x a b c is same as setenv x="a b c".
-	    # a kludge now--the extra single quotes are needed
-	    # else eval complains.
-	    shift
-	    envN=$1
-	    shift
-	    envname=$1
-	    envalue=
-	    while test $envN -gt 0; do
-		shift
-		envalue="$envalue $1"
-		envN=`expr $envN - 1`
-	    done
-	    eval $envname="'$envalue'"
-	    export $envname
 	    ;;
 	srcdir)
 	    #use srcdir option for test
@@ -172,10 +100,6 @@ while [ $# -gt 0 ] ; do
 	    cmd="help"
 	    break
 	    ;;
-	echo)
-	    set -x
-	    break
-	    ;;
 	zlib)
 	    shift
 	    if [ $# -lt 1 ]; then
@@ -186,18 +110,15 @@ while [ $# -gt 0 ] ; do
 	    fi
 	    ZLIB="$1"
 	    ;;
-	releasedir)
+	archive)
 	    shift
 	    if [ $# -lt 1 ]; then
-		echo "Release directory name missing"
+		echo "Archive pathname missing"
 		errcode=1
 		cmd="help"
 		break
 	    fi
-	    ReleaseDir="$1"
-	    ;;
-	check-vfd)
-	    CHECKVAL=check-vfd
+	    ARCHIVES="$1"
 	    ;;
 	--*)
 	    OP_CONFIGURE="$OP_CONFIGURE $1"
@@ -222,35 +143,21 @@ while [ $# -gt 0 ] ; do
     shift
 done
 
-# Dump environment variables after option parsing
-echo ===Dumping environment variables after option parsing ===
-printenv | sort
-echo ===Done Dumping environment variables after option parsing ===
-
 if [ "$cmd" = help ]; then
     set -
     cat <<EOF
-Usage: $PROGNAME [all] [checkout] [diff] [test] [srcdir] [release] [help]
-	[clean] [distclean] [echo] [deploy <dir>] [deploydir <dir>]
-	[zlib <zlib_path>] [releasedir <dir>] [srcdirname <dir>] [check-vfd]
-	[op-configure <option>] [--<option>]
+Usage: $0 [all] [checkout] [diff] [test] [srcdir] [release] [help]
+          [zlib <zlib_path>] [archive <arch_path>] [dir <dir>]
+	  [op-configure <option>] [--<option>]
     all:      Run all commands (checkout, test & release)
               [Default is all]
-    checkout: Run source checkout
+    checkout: Run cvs checkout
     diff:     Run diff on current and previous versions.  Exit 0 if
               no significant differences are found.  Otherwise, non-zero.
-    deploy:   deploy binary to directory <dir>
-    deploydir: use <dir> as the default directory for deployment
     test:     Run test
     release:  Run release
     clean:    Run make clean
     distclean:Run make distclean
-    echo:     Turn on echo mode (set -x)
-    setenv <name> <value>:
-              Set environment variable <name> to <value>.
-    setenvN <N> <name> <value> ...:
-	      Set environment variable with <N> values.
-	      E.g., setenvN 3 x a b c is same as setenv x="a b c".
     srcdir:   Use srcdir option (does not imply other commands)
               "snapshot srcdir" is equivalent to "snapshot srcdir all"
               "snapshot srcdir checkout" is equivalent to "snapshot checkout"
@@ -260,15 +167,12 @@ Usage: $PROGNAME [all] [checkout] [diff] [test] [srcdir] [release] [help]
               E.g., "snapshot srcdir srcdirname -xx" uses hostname-xx
               [Default is hostname]
     help:     Print this message
-    echo:     Turn on shell echo
     zlib <zlib_path>:
               Use <zlib_path> as the ZLIB locations
               [Default is $ZLIB_default]
-    releasedir <dir>:
-              Use <dir> as the release directory
-              [Default is $ReleaseDir_default]
-    check-vfd:
-	      Run make check-vfd instead of just make check.
+    archive <arch_path>:
+              Use <arch_path> as the release ARCHIVE area
+              [Default is $ARCHIVES_default]
     op-configure <option>:
               Pass <option> to the configure command
               E.g., "snapshot op-configure --enable-parallel"
@@ -296,19 +200,13 @@ else
 fi
 
 BASEDIR=${HOME}/snapshots-${H5VERSION}
-if [ ! -d ${BASEDIR} ]; then
-    echo "BASEDIR ($BASEDIR) does not exist"
-    exit 1
-fi
-
 CURRENT=${BASEDIR}/current
 PREVIOUS=${BASEDIR}/previous
-ReleaseDir=${ReleaseDir:=${BASEDIR}/${ReleaseDir_default}}
 HOSTNAME=`hostname | cut -f1 -d.`	# no domain part
 if [ $H5VERSION != hdf5 ]; then
-    SVNVERSION="hdf5/branches/$H5VERSION"
+    CVSVERSION="-r $H5VERSION"
 else
-    SVNVERSION=hdf5/trunk		# use the default (trunk) version
+    CVSVERSION=				# use the default (main) version
 fi
 
 # Try finding a version of diff that supports the -I option too.
@@ -319,13 +217,17 @@ for d in `echo $PATH | sed -e 's/:/ /g'` ; do
 done
 
 #=============================
-# Run source checkout
+# Run CVS checkout
 #=============================
 if [ "$cmd" = "all" -o -n "$cmdcheckout" ]; then
-    TIMESTAMP "checkout"
+    # Create a working directory.  Hopefully one is left over from last
+    # time that still has the contents of the previous release.  But if
+    # not, just create one and assume that a snapshot is necessary.
+    test -d ${BASEDIR} || mkdir -p ${BASEDIR} || exit 1
+
     # If there is a Makefile in ${CURRENT}, the last test done in it
     # has not been distclean'ed.  They would interfere with other
-    # --srcdir build since make considers the files in ${CURRENT}
+    # --srcdir build since make considers the files in ${CURRENT} 
     # take precedence over files in its own build-directory.  Run
     # a "make distclean" to clean them all out.  This is not really
     # part of the "checkout" functions but this is the most convenient
@@ -333,17 +235,15 @@ if [ "$cmd" = "all" -o -n "$cmdcheckout" ]; then
     # regardless of the return code of distclean.
     ( cd ${CURRENT}; test -f Makefile && ${MAKE} distclean)
 
-    SVNROOT=http://svn.hdfgroup.uiuc.edu
-    # Check out the current version from source repository.
-    (cd $BASEDIR; svn -q co ${SVNROOT}/${SVNVERSION} current ) || exit 1
-fi # Do source checkout
+    # Check out the current version from CVS
+    cvs -Q co -d ${CURRENT} ${CVSVERSION} hdf5 || exit 1
+fi # Do CVS checkout
 
 
 #=============================
 # Run Test the HDF5 library
 #=============================
 if [ "$cmd" = "all" -o -n "$cmdtest" -o -n "$cmddiff" ]; then
-    TIMESTAMP "diff"
     # setup if srcdir is used.
     if [ -z "$srcdir" ]; then
 	TESTDIR=${CURRENT}
@@ -360,6 +260,8 @@ if [ "$cmd" = "all" -o -n "$cmdtest" -o -n "$cmddiff" ]; then
 	TESTDIR=${BASEDIR}/TestDir/${SRCDIRNAME}
 	test -d ${TESTDIR} || mkdir ${TESTDIR}
     fi
+    INSTALLDIR=${TESTDIR}/installdir
+    test -d $INSTALLDIR || mkdir $INSTALLDIR
     # Make sure current version exists and is clean
     if [ -d ${TESTDIR} ]; then
 	(cd ${TESTDIR} && ${MAKE} distclean)
@@ -401,18 +303,12 @@ if [ "$cmd" = "all" -o -n "$cmdtest" -o -n "$cmddiff" ]; then
     # Build, run tests and install procedures
     if [ "$snapshot" = "yes" ]; then
 	if (cd ${TESTDIR} && \
-	    TIMESTAMP "configure" && \
-	    ${srcdir:+${CURRENT}/}${CONFIGURE} && \
-	    TIMESTAMP "make" && \
-	    ${MAKE} && DISKUSAGE \
-	    TIMESTAMP ${CHECKVAL} && \
-	    ${MAKE} ${CHECKVAL} && DISKUSAGE \
-	    TIMESTAMP "install" && \
-	    ${MAKE} install-all && DISKUSAGE \
-	    TIMESTAMP "check-install" && \
-	    ${MAKE} check-install && DISKUSAGE \
-	    TIMESTAMP "uninstall" && \
-	    ${MAKE} uninstall-all) && DISKUSAGE ; then
+	    ${srcdir:+${CURRENT}/}${CONFIGURE} --prefix=$INSTALLDIR && \
+	    ${MAKE} && \
+	    ${MAKE} check && \
+	    ${MAKE} install install-doc && \
+	    ${MAKE} check-install && \
+	    ${MAKE} uninstall uninstall-doc); then
 	    :
 	else
 	    errcode=$?
@@ -424,50 +320,27 @@ fi # Test the HDF5 library
 
 
 #=============================
-# Run deployment if requested.
-#=============================
-if [ -n "$DEPLOYDIRNAME" ]; then
-    if [ "$snapshot" = "yes" ]; then
-	TIMESTAMP "deploy"
-        if (cd ${TESTDIR} &&
-            ${CURRENT}/bin/deploy ${deploydir}/${DEPLOYDIRNAME} && \
-            TIMESTAMP "clean" && \
-            ${MAKE} clean && \
-            TIMESTAMP "check-install prefix=${deploydir}/${DEPLOYDIRNAME}" && \
-            ${MAKE} check-install prefix=${deploydir}/${DEPLOYDIRNAME}); then
-	    :	#continue
-	else
-	    errcode=$?
-	    exit $errcode
-	fi
-    fi
-fi # Deploy
-
-
-#=============================
-# Run Release snapshot, update version, and commit to source repository
+# Run Release snapshot, update version, and commit to cvs and tag
 #=============================
 if [ "$cmd" = "all" -o -n "$cmdrel" ]; then
     if [ "$snapshot" = "yes" ]; then
-	TIMESTAMP "release"
 	(cd ${CURRENT} && ${MAKE} distclean)
 	(
 	    # Turn on exit on error in the sub-shell so that it does not
-	    # commit source if errors encounter here.
+	    # cvs commit if errors encounter here.
 	    set -e
 	    cd ${CURRENT}
+	    bin/release -d $ARCHIVES $METHODS
 	    RELEASE_VERSION="`perl bin/h5vers -v`"
-	    echo "Making snapshot release ($RELEASE_VERSION) to ${ReleaseDir}..."
-	    bin/release -d $ReleaseDir $METHODS
 	    perl bin/h5vers -i
-	    svn -q commit -m "Snapshot $RELEASE_VERSION"
+	    cvs -Q commit -m "Snapshot $RELEASE_VERSION"
 	)
 	errcode=$?
     fi
 
     # Replace the previous version with the current version.
     # Should check if the errcode of the release process but there
-    # are other failures after release was done (e.g. h5vers or svn failures)
+    # are other failures after release was done (e.g. h5vers or cvs failures)
     # that should allow the replacement to occure.
     rm -rf ${PREVIOUS}
     mv ${CURRENT} ${PREVIOUS}
@@ -478,7 +351,6 @@ fi #Release snapshot
 # Clean the test area.  Default is no clean.
 #=============================
 if [ -n "$cmdclean" ]; then
-    TIMESTAMP "clean"
     # setup if srcdir is used.
     if [ -z "$srcdir" ]; then
 	TESTDIR=${CURRENT}
@@ -493,9 +365,9 @@ if [ -n "$cmdclean" ]; then
 	esac
 	TESTDIR=${BASEDIR}/TestDir/${SRCDIRNAME}
     fi
-    # clean it
-    if (cd ${TESTDIR} && ${MAKE} $cmdclean ) then
-	:
+    # Make sure current version exists and is clean
+    if [ -d ${TESTDIR} ]; then
+	(cd ${TESTDIR} && ${MAKE} $cmdclean )
     else
 	errcode=$?
         snapshot=no
diff --git a/tools/misc/h5redeploy.in b/tools/misc/h5redeploy.in
--- a/tools/misc/h5redeploy.in
+++ b/tools/misc/h5redeploy.in
@@ -1,22 +1,13 @@
 #! /bin/sh
-#
-# Copyright by The HDF Group.
-# Copyright by the Board of Trustees of the University of Illinois.
-# All rights reserved.
-#
-# This file is part of HDF5.  The full HDF5 copyright notice, including
-# terms governing use, modification, and redistribution, is contained in
-# the files COPYING and Copyright.html.  COPYING can be found at the root
-# of the source code distribution tree; Copyright.html can be found at the
-# root level of an installed copy of the electronic HDF5 document set and
-# is linked from the top-level documents page.  It can also be found at
-# http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
-# access to either file, you may request a copy from help@hdfgroup.org.
-#
+##
+## Copyright (C) 2002
+##     National Center for Supercomputing Applications
+##     All rights reserved.
+##
 
 ## Update HDF5 compiler tools after the HDF5 software has been installed
 ## in a new location.
-## For help page, use "h5redeploy -help"
+## For help page, use "h5redeploy -h"
 
 # Function definitions
 
@@ -25,9 +16,8 @@ usage() {
   # A wonderfully informative "usage" message.
   echo "usage: $prog_name [OPTIONS]"
   echo "  OPTIONS:"
-  echo "    -help|help   This help message"
+  echo "    -help        This help message."
   echo "    -echo        Show all the shell commands executed"
-  echo "    -force       No prompt, just do it"
   echo "    -prefix=DIR  New directory to find HDF5 lib/ and include/"
   echo "                   subdirectories [default: current directory]"
   echo "    -tool=TOOL   Tool to update. TOOL must be in the current"
@@ -49,10 +39,11 @@ dump_vars(){
 show_action()
 {
     echo "Update the following tools because they are now installed at a new directory"
-    for t in $foundtools; do
+    for t in $h5tools; do
 	echo "${t}:"
-	echo "   current setting=`sed -e '/^prefix=/s/prefix=//p' -e d $t`"
-	echo "   new     setting="\""$prefix"\"
+	echo -n "   current setting="
+	sed -e "/^prefix=/s/prefix=//p" -e d $t
+	echo    "   new     setting="\""$prefix"\"
     done
 }
 
@@ -67,9 +58,7 @@ ERROR()
 # Main
 #
 # Initialization
-h5tools="h5cc h5pcc h5fc h5pfc h5c++"	# possible hdf5 tools
-foundtools=		# tools found and will be modified
-fmode=			# force mode, default is off
+h5tools=h5cc
 prefix=`(cd ..;pwd)`
 
 # Parse options
@@ -90,9 +79,6 @@ for arg in $@ ; do
     -help|help)
       usage
       ;;
-    -force)
-      fmode=yes
-      ;;
     *)
       ERROR "Unknown Option($arg)"
       usage
@@ -108,31 +94,21 @@ if [ ! -d $prefix ]; then
 fi
 
 for x in $h5tools; do
-    if [ -f $x ]; then
-	foundtools="$foundtools $x"
-	if [ ! -w $x ]; then
-	    ERROR "h5tool($x) is not writable"
-	    exit 1
-	fi
+    if [ ! -w $x ]; then
+	ERROR "h5tool($h5tools) is not found in the current directory or is not writable"
+	exit 1
     fi
 done
-
-if [ -z "$foundtools" ]; then
-    ERROR "found no tools to modify"
-    exit 1
-fi
+	
 
 # Show actions to be taken and get consent
 show_action
-# Ask confirmation unless fmode is on
-if [ x-$fmode = x- ]; then
-    echo "Continue? (yes/no)"
-    read ansx
-    ans=`echo $ansx | tr "[A-Z]" "[a-z]"`
-    if [ x-$ans != x-yes ]; then
-	echo ABORT.  No tools changed.
-	exit 1
-    fi
+echo -n "Continue? (yes/no)"
+read ansx
+ans=`echo $ansx | tr "[A-Z]" "[a-z]"`
+if [ x-$ans != x-yes ]; then
+    echo ABORT.  No tools changed.
+    exit 1
 fi
 
 
@@ -153,7 +129,7 @@ if [ "$SHOW" = "echo" ]; then
     echo "===End Update commands====="
 fi
 
-for t in $foundtools; do
+for t in $h5tools; do
     echo Update $t ...
     COMMAND="ed - $t"
     if [ "$SHOW" = "echo" ]; then
